"""url can be not unique

Revision ID: 0a4d8ea0e3f3
Revises: 1bd1160b469c
Create Date: 2026-01-04 23:54:16.099314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4d8ea0e3f3'
down_revision: Union[str, Sequence[str], None] = '1bd1160b469c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('urls_url_key'), 'urls', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('urls_url_key'), 'urls', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
