"""Init new migrations. Add trigger for insert recort into revision code

Revision ID: 1bd1160b469c
Revises: 
Create Date: 2026-01-04 16:10:16.141917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd1160b469c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_urls_slug'), 'urls', ['slug'], unique=True)
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE FUNCTION generate_slug()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.slug := translate(
                encode(
                    substring(decode(lpad(to_hex(NEW.id), 16, '0'), 'hex'), 1, 11),
                    'base64'
                ),
                '+/', '-_'
            );
            NEW.slug := regexp_replace(NEW.slug, '=+$', '');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER set_slug_trigger
        BEFORE INSERT ON urls
        FOR EACH ROW
        WHEN (NEW.slug IS NULL OR NEW.slug = '')
        EXECUTE FUNCTION generate_slug();
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_slug'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###

    op.execute("DROP TRIGGER IF EXISTS set_slug_trigger ON urls;")
    op.execute("DROP FUNCTION IF EXISTS generate_slug();")
