"""url необязательно должен быть уникальным в нашем сценарии

Revision ID: de5eaded11b4
Revises: cc84fb2f2307
Create Date: 2025-12-28 23:17:25.418310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5eaded11b4'
down_revision: Union[str, Sequence[str], None] = 'cc84fb2f2307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('urls_url_key'), 'urls', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('urls_url_key'), 'urls', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
